"""Catálogo de emojis para o seletor.

Dados, e não dependência. Existem pacotes prontos com os 3.600 emojis do
Unicode e seus nomes oficiais em inglês, mas o que se usa ao escrever uma nota
em português é um conjunto pequeno, e procurar "feliz" ou "coração" precisa
funcionar — o nome oficial é ``grinning face with smiling eyes``.

As palavras-chave são em português, com alguns sinônimos em inglês para quem
digita ``done`` esperando um ✅.
"""

from __future__ import annotations

import unicodedata
from dataclasses import dataclass, field


@dataclass(frozen=True)
class Emoji:
    """Um emoji e como encontrá-lo."""

    char: str
    name: str
    keywords: tuple[str, ...] = field(default_factory=tuple)

    def haystack(self) -> str:
        """Texto normalizado usado na busca."""
        return normalize(" ".join((self.name, *self.keywords)))


def normalize(text: str) -> str:
    """Minúsculas e sem acento, para a busca não depender de digitação exata."""
    decomposto = unicodedata.normalize("NFKD", text.lower())
    return "".join(c for c in decomposto if not unicodedata.combining(c))


#: Categorias na ordem em que aparecem no seletor.
CATEGORIES: dict[str, tuple[Emoji, ...]] = {
    "Carinhas": (
        Emoji("😀", "Sorriso aberto", ("feliz", "alegre", "grin")),
        Emoji("😃", "Sorriso", ("feliz", "alegre")),
        Emoji("😄", "Sorriso com olhos felizes", ("feliz", "rindo")),
        Emoji("😁", "Sorriso radiante", ("feliz", "dentes")),
        Emoji("😆", "Rindo alto", ("risada", "gargalhada", "lol")),
        Emoji("😅", "Sorriso com suor", ("alivio", "ufa")),
        Emoji("🤣", "Rolando de rir", ("risada", "gargalhada", "lol")),
        Emoji("😂", "Lágrimas de alegria", ("risada", "chorando de rir")),
        Emoji("🙂", "Sorriso leve", ("ok", "tudo bem")),
        Emoji("🙃", "Sorriso invertido", ("ironia", "sarcasmo")),
        Emoji("😉", "Piscadela", ("wink", "brincadeira")),
        Emoji("😊", "Sorriso tímido", ("feliz", "envergonhado")),
        Emoji("😇", "Anjo", ("inocente", "santo")),
        Emoji("🥰", "Apaixonado", ("amor", "carinho", "corações")),
        Emoji("😍", "Olhos de coração", ("amor", "apaixonado", "coracao")),
        Emoji("❤️", "Coração vermelho", ("amor", "coracao", "heart")),
        Emoji("💔", "Coração partido", ("amor", "coracao partido", "triste")),
        Emoji("💕", "Dois corações", ("amor", "coracoes")),
        Emoji("💖", "Coração brilhante", ("amor", "coracao")),
        Emoji("👀", "Olhos", ("olhar", "atenção", "eyes", "vendo")),
        Emoji("🤩", "Olhos de estrela", ("impressionado", "uau")),
        Emoji("😘", "Beijo", ("beijo", "amor")),
        Emoji("😗", "Beijinho", ("beijo",)),
        Emoji("😋", "Saboreando", ("gostoso", "delicia", "hum")),
        Emoji("😛", "Língua de fora", ("brincadeira",)),
        Emoji("🤪", "Carinha doida", ("louco", "zoeira")),
        Emoji("🤨", "Sobrancelha erguida", ("desconfiado", "suspeita")),
        Emoji("🧐", "Monóculo", ("analisando", "investigando")),
        Emoji("🤓", "Nerd", ("estudo", "oculos", "nerd")),
        Emoji("😎", "Óculos escuros", ("cool", "tranquilo")),
        Emoji("🥳", "Festa", ("comemorando", "aniversario", "festa")),
        Emoji("😏", "Sorrindo de lado", ("malicia", "esperto")),
        Emoji("😒", "Descontente", ("irritado", "enfadado")),
        Emoji("😞", "Desapontado", ("triste", "decepcionado")),
        Emoji("😔", "Pensativo", ("triste", "cabeca baixa")),
        Emoji("😟", "Preocupado", ("preocupacao", "ansioso")),
        Emoji("😕", "Confuso", ("confusao", "nao entendi")),
        Emoji("🙁", "Triste leve", ("triste",)),
        Emoji("😣", "Perseverante", ("esforco", "insistindo")),
        Emoji("😖", "Angustiado", ("sofrimento",)),
        Emoji("😫", "Cansado", ("exausto", "cansaco")),
        Emoji("😩", "Fatigado", ("cansado", "exausto")),
        Emoji("🥺", "Suplicante", ("por favor", "carinha de pidão")),
        Emoji("😢", "Chorando", ("triste", "lagrima", "choro")),
        Emoji("😭", "Chorando muito", ("triste", "choro", "desespero")),
        Emoji("😤", "Bufando", ("bravo", "determinado")),
        Emoji("😠", "Bravo", ("raiva", "irritado")),
        Emoji("😡", "Furioso", ("raiva", "furioso")),
        Emoji("🤬", "Pragas", ("raiva", "xingando")),
        Emoji("🤯", "Cabeça explodindo", ("chocado", "mente explodida")),
        Emoji("😳", "Corado", ("envergonhado", "chocado")),
        Emoji("🥵", "Calor", ("quente", "calor")),
        Emoji("🥶", "Frio", ("frio", "congelando")),
        Emoji("😱", "Gritando de medo", ("medo", "susto", "panico")),
        Emoji("😨", "Assustado", ("medo", "receio")),
        Emoji("😰", "Ansioso com suor", ("ansiedade", "nervoso")),
        Emoji("🤗", "Abraço", ("abraco", "carinho")),
        Emoji("🤔", "Pensando", ("duvida", "pensando", "hmm")),
        Emoji("🤭", "Rindo com a mão na boca", ("risinho", "opa")),
        Emoji("🤫", "Silêncio", ("segredo", "shh", "quieto")),
        Emoji("😐", "Neutro", ("indiferente", "sem expressao")),
        Emoji("😑", "Sem expressão", ("indiferente",)),
        Emoji("😶", "Sem boca", ("silencioso",)),
        Emoji("😴", "Dormindo", ("sono", "dormir", "zzz")),
        Emoji("🤤", "Babando", ("vontade", "desejo")),
        Emoji("😪", "Sonolento", ("sono", "cansado")),
        Emoji("😵", "Tonto", ("tonto", "atordoado")),
        Emoji("🤐", "Boca fechada", ("calado", "segredo")),
        Emoji("🥴", "Embriagado", ("tonto", "bebado")),
        Emoji("🤢", "Enjoado", ("nausea", "enjoo")),
        Emoji("🤮", "Vomitando", ("vomito", "nausea")),
        Emoji("🤧", "Espirrando", ("espirro", "gripe", "resfriado")),
        Emoji("😷", "Máscara", ("doente", "mascara", "gripe")),
        Emoji("🤒", "Termômetro", ("febre", "doente")),
        Emoji("🤕", "Cabeça enfaixada", ("machucado", "ferido")),
        Emoji("🤑", "Dinheiro na boca", ("dinheiro", "rico")),
        Emoji("🤠", "Caubói", ("cowboy", "chapeu")),
        Emoji("👻", "Fantasma", ("halloween", "fantasma")),
        Emoji("💀", "Caveira", ("morte", "morto", "skull")),
        Emoji("👽", "Alienígena", ("alien", "extraterrestre")),
        Emoji("🤖", "Robô", ("robo", "bot", "ia")),
        Emoji("🎃", "Abóbora", ("halloween", "abobora")),
        Emoji("😈", "Diabinho sorrindo", ("diabo", "travesso")),
        Emoji("👹", "Ogros", ("monstro", "ogro")),
    ),
    "Gestos": (
        Emoji("👍", "Joinha", ("positivo", "ok", "curtir", "aprovado", "like")),
        Emoji("👎", "Joinha para baixo", ("negativo", "reprovado", "dislike")),
        Emoji("👌", "Okay", ("ok", "perfeito", "certinho")),
        Emoji("🤌", "Dedos juntos", ("gesto italiano",)),
        Emoji("🤏", "Beliscando", ("pouco", "pequeno")),
        Emoji("✌️", "Paz e amor", ("vitoria", "paz", "dois")),
        Emoji("🤞", "Dedos cruzados", ("sorte", "torcendo")),
        Emoji("🤟", "Te amo", ("amor", "lingua de sinais")),
        Emoji("🤘", "Rock", ("rock", "chifres")),
        Emoji("🤙", "Me liga", ("ligar", "telefone", "shaka")),
        Emoji("👈", "Apontando para a esquerda", ("esquerda", "apontar")),
        Emoji("👉", "Apontando para a direita", ("direita", "apontar")),
        Emoji("👆", "Apontando para cima", ("cima", "acima", "apontar")),
        Emoji("👇", "Apontando para baixo", ("baixo", "abaixo", "apontar")),
        Emoji("☝️", "Indicador para cima", ("um", "primeiro", "cima")),
        Emoji("✋", "Mão levantada", ("pare", "alto", "mao")),
        Emoji("🤚", "Costas da mão", ("mao",)),
        Emoji("🖐️", "Mão aberta", ("cinco", "mao aberta")),
        Emoji("🖖", "Saudação vulcana", ("spock", "vulcano")),
        Emoji("👋", "Acenando", ("oi", "tchau", "ola", "wave")),
        Emoji("🤝", "Aperto de mão", ("acordo", "parceria", "feito")),
        Emoji("🙏", "Mãos juntas", ("por favor", "obrigado", "reza", "gratidao")),
        Emoji("✊", "Punho", ("forca", "punho")),
        Emoji("👊", "Soquinho", ("punho", "bate aqui")),
        Emoji("🤛", "Punho esquerdo", ("punho",)),
        Emoji("🤜", "Punho direito", ("punho",)),
        Emoji("👏", "Palmas", ("aplauso", "parabens", "bravo")),
        Emoji("🙌", "Mãos para cima", ("viva", "comemoracao", "uau")),
        Emoji("👐", "Mãos abertas", ("aberto", "maos")),
        Emoji("🤲", "Mãos em concha", ("receber", "oferta")),
        Emoji("💪", "Bíceps", ("forca", "musculo", "forte")),
        Emoji("🦾", "Braço mecânico", ("protese", "robotico")),
        Emoji("✍️", "Escrevendo", ("escrever", "assinar")),
        Emoji("🫡", "Continência", ("saldo", "sim senhor")),
        Emoji("🖕", "Dedo do meio", ("xingamento", "ofensa")),
    ),
    "Pessoas": (
        Emoji("👶", "Bebê", ("bebe", "crianca")),
        Emoji("🧒", "Criança", ("crianca",)),
        Emoji("👦", "Menino", ("garoto",)),
        Emoji("👧", "Menina", ("garota",)),
        Emoji("🧑", "Pessoa", ("adulto",)),
        Emoji("👨", "Homem", ("homem",)),
        Emoji("👩", "Mulher", ("mulher",)),
        Emoji("🧓", "Idoso", ("velho", "idoso")),
        Emoji("👴", "Homem idoso", ("idoso", "avo")),
        Emoji("👵", "Mulher idosa", ("idosa", "avo")),
        Emoji("👮", "Policial", ("policia", "seguranca")),
        Emoji("👷", "Operário", ("obra", "construcao", "capacete")),
        Emoji("🧑‍💻", "Programador", ("dev", "programador", "codigo")),
        Emoji("🧑‍🏫", "Professor", ("professor", "aula", "ensino")),
        Emoji("🧑‍⚕️", "Profissional de saúde", ("medico", "saude")),
        Emoji("🧑‍🍳", "Cozinheiro", ("chef", "cozinha")),
        Emoji("🕵️", "Detetive", ("investigacao", "detetive")),
        Emoji("💁", "Informando", ("informacao", "atendimento")),
        Emoji("🙋", "Levantando a mão", ("pergunta", "eu sei", "voluntario")),
        Emoji("🙆", "Sinal de ok com os braços", ("ok", "certo")),
        Emoji("🙅", "Não pode", ("nao", "proibido", "negativo")),
        Emoji("🤦", "Mão no rosto", ("vergonha", "nao acredito")),
        Emoji("🤷", "Encolhendo os ombros", ("nao sei", "tanto faz")),
        Emoji("💃", "Dançando", ("danca", "festa")),
        Emoji("🕺", "Homem dançando", ("danca", "festa")),
        Emoji("🚶", "Caminhando", ("caminhada", "andando")),
        Emoji("🏃", "Correndo", ("corrida", "pressa")),
        Emoji("🧘", "Meditando", ("meditacao", "yoga", "calma")),
        Emoji("👥", "Duas pessoas", ("grupo", "equipe", "pessoas")),
        Emoji("👤", "Uma pessoa", ("usuario", "perfil", "pessoa")),
        Emoji("👪", "Família", ("familia", "casa")),
    ),
    "Animais": (
        Emoji("🐶", "Cachorro", ("cao", "cachorro", "pet")),
        Emoji("🐱", "Gato", ("gato", "pet")),
        Emoji("🐭", "Rato", ("rato", "mouse")),
        Emoji("🐹", "Hamster", ("hamster", "roedor")),
        Emoji("🐰", "Coelho", ("coelho", "pascoa")),
        Emoji("🦊", "Raposa", ("raposa",)),
        Emoji("🐻", "Urso", ("urso",)),
        Emoji("🐼", "Panda", ("panda",)),
        Emoji("🐨", "Coala", ("coala",)),
        Emoji("🐯", "Tigre", ("tigre",)),
        Emoji("🦁", "Leão", ("leao",)),
        Emoji("🐮", "Vaca", ("vaca", "boi")),
        Emoji("🐷", "Porco", ("porco", "suino")),
        Emoji("🐸", "Sapo", ("sapo", "ra")),
        Emoji("🐵", "Macaco", ("macaco", "mico")),
        Emoji("🐔", "Galinha", ("galinha", "frango")),
        Emoji("🐧", "Pinguim", ("pinguim",)),
        Emoji("🐦", "Pássaro", ("passaro", "ave")),
        Emoji("🦆", "Pato", ("pato",)),
        Emoji("🦅", "Águia", ("aguia",)),
        Emoji("🦉", "Coruja", ("coruja", "sabedoria")),
        Emoji("🐴", "Cavalo", ("cavalo",)),
        Emoji("🦄", "Unicórnio", ("unicornio", "fantasia")),
        Emoji("🐝", "Abelha", ("abelha", "mel")),
        Emoji("🐛", "Lagarta", ("lagarta", "inseto", "bug")),
        Emoji("🦋", "Borboleta", ("borboleta",)),
        Emoji("🐌", "Caracol", ("caracol", "lento")),
        Emoji("🐞", "Joaninha", ("joaninha", "inseto", "bug", "defeito")),
        Emoji("🐜", "Formiga", ("formiga",)),
        Emoji("🕷️", "Aranha", ("aranha",)),
        Emoji("🐢", "Tartaruga", ("tartaruga", "lento")),
        Emoji("🐍", "Cobra", ("cobra", "serpente")),
        Emoji("🐙", "Polvo", ("polvo",)),
        Emoji("🦀", "Caranguejo", ("caranguejo",)),
        Emoji("🐠", "Peixe tropical", ("peixe",)),
        Emoji("🐟", "Peixe", ("peixe",)),
        Emoji("🐳", "Baleia", ("baleia",)),
        Emoji("🐬", "Golfinho", ("golfinho",)),
        Emoji("🦈", "Tubarão", ("tubarao",)),
        Emoji("🐊", "Jacaré", ("jacare", "crocodilo")),
        Emoji("🐘", "Elefante", ("elefante",)),
        Emoji("🦒", "Girafa", ("girafa",)),
        Emoji("🐺", "Lobo", ("lobo",)),
        Emoji("🐗", "Javali", ("javali",)),
        Emoji("🐎", "Cavalo correndo", ("cavalo", "corrida")),
        Emoji("🌵", "Cacto", ("cacto", "deserto", "planta")),
        Emoji("🌲", "Árvore", ("arvore", "pinheiro")),
        Emoji("🌳", "Árvore frondosa", ("arvore",)),
        Emoji("🌴", "Palmeira", ("palmeira", "praia", "tropical")),
        Emoji("🌱", "Muda", ("planta", "broto", "crescimento")),
        Emoji("🌿", "Erva", ("planta", "folha", "verde")),
        Emoji("🍀", "Trevo de quatro folhas", ("sorte", "trevo")),
        Emoji("🍁", "Folha de bordo", ("outono", "folha", "canada")),
        Emoji("🌸", "Flor de cerejeira", ("flor", "primavera", "sakura")),
        Emoji("🌹", "Rosa", ("rosa", "flor", "amor")),
        Emoji("🌻", "Girassol", ("girassol", "flor")),
        Emoji("🌷", "Tulipa", ("tulipa", "flor")),
        Emoji("🌈", "Arco-íris", ("arco iris", "cores", "lgbt")),
        Emoji("⭐", "Estrela", ("estrela", "favorito", "star")),
        Emoji("🌟", "Estrela brilhante", ("estrela", "brilho")),
        Emoji("✨", "Brilhos", ("brilho", "magia", "sparkles")),
        Emoji("⚡", "Raio", ("energia", "rapido", "raio")),
        Emoji("🔥", "Fogo", ("fogo", "quente", "otimo", "fire")),
        Emoji("💧", "Gota", ("agua", "gota")),
        Emoji("❄️", "Floco de neve", ("neve", "frio", "inverno")),
        Emoji("🌙", "Lua", ("lua", "noite")),
        Emoji("☀️", "Sol", ("sol", "dia", "claro")),
        Emoji("⛅", "Sol com nuvem", ("nublado", "tempo")),
        Emoji("☁️", "Nuvem", ("nuvem", "nublado")),
        Emoji("🌧️", "Chuva", ("chuva", "tempo")),
        Emoji("⛈️", "Tempestade", ("tempestade", "trovao", "chuva")),
        Emoji("🌊", "Onda", ("onda", "mar", "agua")),
    ),
    "Comida": (
        Emoji("🍎", "Maçã", ("maca", "fruta")),
        Emoji("🍌", "Banana", ("banana", "fruta")),
        Emoji("🍇", "Uvas", ("uva", "fruta")),
        Emoji("🍓", "Morango", ("morango", "fruta")),
        Emoji("🍊", "Tangerina", ("laranja", "fruta")),
        Emoji("🍋", "Limão", ("limao", "fruta")),
        Emoji("🍉", "Melancia", ("melancia", "fruta")),
        Emoji("🍍", "Abacaxi", ("abacaxi", "fruta")),
        Emoji("🥑", "Abacate", ("abacate", "fruta")),
        Emoji("🍅", "Tomate", ("tomate", "legume")),
        Emoji("🥕", "Cenoura", ("cenoura", "legume")),
        Emoji("🌽", "Milho", ("milho", "legume")),
        Emoji("🥔", "Batata", ("batata", "legume")),
        Emoji("🍞", "Pão", ("pao", "padaria")),
        Emoji("🥐", "Croissant", ("croissant", "padaria")),
        Emoji("🧀", "Queijo", ("queijo",)),
        Emoji("🍳", "Ovo frito", ("ovo", "fritura", "cafe da manha")),
        Emoji("🥗", "Salada", ("salada", "saudavel")),
        Emoji("🍕", "Pizza", ("pizza", "italiana")),
        Emoji("🍔", "Hambúrguer", ("hamburguer", "lanche", "burger")),
        Emoji("🍟", "Batata frita", ("fritas", "lanche")),
        Emoji("🌭", "Cachorro-quente", ("hot dog", "lanche")),
        Emoji("🌮", "Taco", ("taco", "mexicano")),
        Emoji("🍣", "Sushi", ("sushi", "japones")),
        Emoji("🍜", "Macarrão", ("macarrao", "lamen", "sopa")),
        Emoji("🍚", "Arroz", ("arroz",)),
        Emoji("🍛", "Curry com arroz", ("curry", "arroz")),
        Emoji("🍲", "Panela de comida", ("cozido", "sopa", "refeicao")),
        Emoji("🥘", "Caçarola", ("panela", "refeicao")),
        Emoji("🍱", "Marmita", ("marmita", "bento", "almoco")),
        Emoji("🍰", "Bolo", ("bolo", "doce", "aniversario")),
        Emoji("🎂", "Bolo de aniversário", ("aniversario", "bolo", "parabens")),
        Emoji("🍫", "Chocolate", ("chocolate", "doce")),
        Emoji("🍬", "Bala", ("doce", "bala")),
        Emoji("🍭", "Pirulito", ("pirulito", "doce")),
        Emoji("🍩", "Rosquinha", ("donut", "doce")),
        Emoji("🍪", "Biscoito", ("biscoito", "cookie")),
        Emoji("☕", "Café", ("cafe", "bebida", "cafeina")),
        Emoji("🍵", "Chá", ("cha", "bebida")),
        Emoji("🧉", "Mate", ("mate", "chimarrao")),
        Emoji("🥤", "Copo com canudo", ("refrigerante", "bebida")),
        Emoji("🍺", "Cerveja", ("cerveja", "bebida", "bar")),
        Emoji("🍻", "Brinde", ("brinde", "cerveja", "saude")),
        Emoji("🍷", "Vinho", ("vinho", "bebida")),
        Emoji("🥂", "Taças brindando", ("brinde", "espumante", "comemoracao")),
    ),
    "Atividades": (
        Emoji("✅", "Certo", ("ok", "concluido", "feito", "check", "done")),
        Emoji("❌", "Errado", ("erro", "nao", "x", "cancelado")),
        Emoji("⚠️", "Aviso", ("atencao", "aviso", "cuidado", "warning")),
        Emoji("❗", "Exclamação", ("atencao", "importante")),
        Emoji("❓", "Interrogação", ("duvida", "pergunta")),
        Emoji("💡", "Lâmpada", ("ideia", "dica", "insight")),
        Emoji("🔔", "Sino", ("notificacao", "lembrete", "alerta")),
        Emoji("🔕", "Sino silenciado", ("silencioso", "sem notificacao")),
        Emoji("📌", "Alfinete", ("fixar", "importante", "pin")),
        Emoji("📍", "Alfinete de mapa", ("local", "aqui", "posicao")),
        Emoji("🔗", "Corrente", ("link", "ligacao", "url")),
        Emoji("📎", "Clipe", ("anexo", "anexar", "clip")),
        Emoji("📁", "Pasta", ("pasta", "diretorio", "arquivos")),
        Emoji("📂", "Pasta aberta", ("pasta", "abrir")),
        Emoji("📄", "Documento", ("arquivo", "documento", "pagina")),
        Emoji("📝", "Anotação", ("anotacao", "nota", "escrever", "rascunho")),
        Emoji("📋", "Prancheta", ("copiar", "lista", "clipboard")),
        Emoji("📊", "Gráfico de barras", ("grafico", "dados", "relatorio")),
        Emoji("📈", "Gráfico subindo", ("crescimento", "alta", "grafico")),
        Emoji("📉", "Gráfico caindo", ("queda", "baixa", "grafico")),
        Emoji("📅", "Calendário", ("data", "calendario", "agenda")),
        Emoji("⏰", "Despertador", ("hora", "alarme", "tempo")),
        Emoji("⏳", "Ampulheta", ("tempo", "espera", "prazo")),
        Emoji("🔍", "Lupa", ("buscar", "pesquisa", "procurar", "search")),
        Emoji("🔒", "Cadeado fechado", ("seguranca", "bloqueado", "privado")),
        Emoji("🔓", "Cadeado aberto", ("aberto", "liberado")),
        Emoji("🔑", "Chave", ("chave", "acesso", "senha")),
        Emoji("🛠️", "Ferramentas", ("ferramenta", "manutencao", "config")),
        Emoji("⚙️", "Engrenagem", ("configuracao", "ajuste", "settings")),
        Emoji("🧪", "Tubo de ensaio", ("teste", "experimento", "laboratorio")),
        Emoji("🚀", "Foguete", ("lancamento", "rapido", "deploy", "startup")),
        Emoji("🎯", "Alvo", ("objetivo", "meta", "foco", "target")),
        Emoji("🏆", "Troféu", ("premio", "vitoria", "conquista")),
        Emoji("🥇", "Medalha de ouro", ("primeiro", "premio", "ouro")),
        Emoji("🎉", "Festa", ("comemoracao", "parabens", "festa", "viva")),
        Emoji("🎊", "Confete", ("comemoracao", "festa")),
        Emoji("🎁", "Presente", ("presente", "brinde", "gift")),
        Emoji("🎈", "Balão", ("festa", "comemoracao")),
        Emoji("🎵", "Nota musical", ("musica", "som", "audio")),
        Emoji("🎬", "Claquete", ("filme", "video", "cinema")),
        Emoji("🎮", "Controle de videogame", ("jogo", "game", "videogame")),
        Emoji("⚽", "Futebol", ("futebol", "bola", "esporte")),
        Emoji("🏀", "Basquete", ("basquete", "esporte")),
        Emoji("🏈", "Futebol americano", ("esporte",)),
        Emoji("🎾", "Tênis", ("tenis", "esporte")),
        Emoji("🏋️", "Halterofilismo", ("academia", "treino", "peso")),
        Emoji("🚴", "Ciclismo", ("bicicleta", "ciclismo", "esporte")),
        Emoji("🏊", "Natação", ("natacao", "piscina", "esporte")),
        Emoji("⛹️", "Basquete quicando", ("esporte",)),
        Emoji("🧩", "Quebra-cabeça", ("puzzle", "peca", "quebra-cabeca")),
        Emoji("♟️", "Peão de xadrez", ("xadrez", "estrategia")),
        Emoji("🎨", "Paleta de tinta", ("arte", "pintura", "design")),
    ),
    "Objetos": (
        Emoji("💻", "Notebook", ("computador", "laptop", "dev")),
        Emoji("🖥️", "Monitor", ("computador", "desktop", "tela")),
        Emoji("⌨️", "Teclado", ("teclado", "digitar")),
        Emoji("🖱️", "Mouse", ("mouse", "clique")),
        Emoji("🖨️", "Impressora", ("impressora", "imprimir")),
        Emoji("💾", "Disquete", ("salvar", "save", "disquete")),
        Emoji("💿", "CD", ("cd", "disco")),
        Emoji("📱", "Celular", ("celular", "telefone", "smartphone")),
        Emoji("☎️", "Telefone", ("telefone", "ligar")),
        Emoji("📞", "Gancho de telefone", ("ligacao", "telefone")),
        Emoji("📧", "E-mail", ("email", "mensagem", "correio")),
        Emoji("📨", "Envelope chegando", ("email", "mensagem")),
        Emoji("📦", "Pacote", ("pacote", "entrega", "caixa")),
        Emoji("📮", "Caixa de correio", ("correio", "enviar")),
        Emoji("📰", "Jornal", ("noticia", "jornal")),
        Emoji("📚", "Livros", ("livro", "estudo", "biblioteca")),
        Emoji("📖", "Livro aberto", ("livro", "leitura", "documentacao")),
        Emoji("📕", "Livro fechado", ("livro",)),
        Emoji("✏️", "Lápis", ("lapis", "escrever", "editar")),
        Emoji("🖊️", "Caneta", ("caneta", "escrever")),
        Emoji("🖌️", "Pincel", ("pincel", "pintar", "design")),
        Emoji("📏", "Régua", ("regua", "medir")),
        Emoji("✂️", "Tesoura", ("tesoura", "cortar", "recortar")),
        Emoji("🗑️", "Lixeira", ("lixeira", "excluir", "deletar")),
        Emoji("🔨", "Martelo", ("martelo", "construir")),
        Emoji("🔧", "Chave inglesa", ("chave", "consertar", "ajuste")),
        Emoji("🔩", "Parafuso", ("parafuso", "porca")),
        Emoji("🧲", "Ímã", ("ima", "atracao")),
        Emoji("💊", "Comprimido", ("remedio", "saude", "medicamento")),
        Emoji("🩺", "Estetoscópio", ("medico", "saude", "consulta")),
        Emoji("🔬", "Microscópio", ("microscopio", "laboratorio")),
        Emoji("🔭", "Telescópio", ("telescopio", "astronomia")),
        Emoji("🔋", "Bateria", ("bateria", "energia", "carga")),
        Emoji("🔌", "Tomada", ("tomada", "energia", "plug")),
        Emoji("💰", "Saco de dinheiro", ("dinheiro", "grana", "financas")),
        Emoji("💵", "Nota de dólar", ("dinheiro", "dolar")),
        Emoji("💳", "Cartão de crédito", ("cartao", "pagamento", "credito")),
        Emoji("🧾", "Recibo", ("recibo", "nota fiscal", "comprovante")),
        Emoji("⚖️", "Balança", ("justica", "balanca", "lei")),
        Emoji("🛡️", "Escudo", ("protecao", "seguranca", "defesa")),
        Emoji("🏠", "Casa", ("casa", "lar", "home")),
        Emoji("🏢", "Edifício", ("predio", "empresa", "escritorio")),
        Emoji("🚗", "Carro", ("carro", "veiculo", "automovel")),
        Emoji("✈️", "Avião", ("aviao", "viagem", "voo")),
        Emoji("🚢", "Navio", ("navio", "barco", "mar")),
        Emoji("🚲", "Bicicleta", ("bicicleta", "bike")),
        Emoji("🚂", "Trem", ("trem", "locomotiva")),
        Emoji("🗺️", "Mapa", ("mapa", "localizacao", "rota")),
        Emoji("🧭", "Bússola", ("bussola", "direcao")),
        Emoji("⛺", "Barraca", ("acampamento", "barraca", "camping")),
        Emoji("🌍", "Globo terrestre", ("mundo", "terra", "global", "planeta")),
        Emoji("🎓", "Chapéu de formatura", ("formacao", "estudo", "diploma")),
        Emoji("⏱️", "Cronômetro", ("tempo", "cronometro")),
        Emoji("📢", "Megafone", ("anuncio", "aviso", "divulgacao")),
        Emoji("📣", "Corneta", ("anuncio", "divulgacao")),
        Emoji("🔊", "Alto-falante", ("som", "audio", "volume")),
        Emoji("🔇", "Som desligado", ("mudo", "sem som")),
    ),
}

#: Apelido curto -> emoji, para a busca achar por atalho do GitHub.
#: Escrever ``:tada:`` no GitHub e no Slack é hábito, e quem procura por
#: "tada" espera o 🎉.
ALIASES: dict[str, str] = {
    "tada": "🎉",
    "rocket": "🚀",
    "bug": "🐞",
    "fire": "🔥",
    "star": "⭐",
    "sparkles": "✨",
    "check": "✅",
    "done": "✅",
    "x": "❌",
    "warning": "⚠️",
    "bulb": "💡",
    "book": "📚",
    "memo": "📝",
    "lock": "🔒",
    "key": "🔑",
    "gear": "⚙️",
    "wrench": "🔧",
    "link": "🔗",
    "search": "🔍",
    "heart": "❤️",
    "thumbsup": "👍",
    "thumbsdown": "👎",
    "ok_hand": "👌",
    "clap": "👏",
    "pray": "🙏",
    "muscle": "💪",
    "eyes": "👀",
    "thinking": "🤔",
    "sob": "😭",
    "joy": "😂",
    "sunglasses": "😎",
    "coffee": "☕",
    "beer": "🍺",
    "pizza": "🍕",
    "cake": "🎂",
    "gift": "🎁",
    "trophy": "🏆",
    "medal": "🥇",
    "chart": "📈",
    "calendar": "📅",
    "clock": "⏰",
    "folder": "📁",
    "package": "📦",
    "shield": "🛡️",
    "globe": "🌍",
    "home": "🏠",
}


def all_emojis() -> tuple[Emoji, ...]:
    """Todos os emojis, na ordem das categorias."""
    return tuple(e for grupo in CATEGORIES.values() for e in grupo)


def by_category(name: str) -> tuple[Emoji, ...]:
    """Emojis de uma categoria; lista vazia se o nome não existir."""
    return CATEGORIES.get(name, ())


def search(query: str, limit: int = 0) -> tuple[Emoji, ...]:
    """Emojis cujo nome ou palavra-chave contenham ``query``.

    A comparação ignora caixa e acento: quem digita "coracao" precisa achar
    "Coração". Um apelido exato (``:tada:``) tem prioridade e vem primeiro.

    ``limit`` maior que zero corta o resultado; o padrão devolve tudo.
    """
    termo = normalize(query.strip().strip(":"))
    if not termo:
        return all_emojis()

    if termo in ALIASES:
        alvo = ALIASES[termo]
        exato = tuple(e for e in all_emojis() if e.char == alvo)
        if exato:
            return exato

    encontrados = tuple(e for e in all_emojis() if termo in e.haystack())
    return encontrados[:limit] if limit > 0 else encontrados


def categories() -> tuple[str, ...]:
    """Nomes das categorias, na ordem do seletor."""
    return tuple(CATEGORIES)
